# Generated by Django 2.2.3 on 2019-08-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190815_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='userid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
