# Generated by Django 2.2.3 on 2019-08-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
