# Generated by Django 2.2.3 on 2019-08-13 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='attachment',
        ),
    ]
